apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: default
  labels:
    app: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
          image: ghcr.io/gorlah/k8s-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-service.mongo/k8s_demo
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: k8s-demo.erichaag.io
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: k8s-demo
                port:
                  number: 8080
            path: /
  tls:
    - hosts:
        - k8s-demo.erichaag.io
      secretName: erichaag-io-tls-secret
