services:
  mongo:
    image: mongo:5.0.1
    volumes:
      - mongo_data:/data/db
  k8s-demo:
    image: ghcr.io/gorlah/k8s-demo:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo/k8s_demo
volumes:
  mongo_data:
